### ISSUE TITLE
Kerberos.io integration

### ISSUE THREAD

**Issue by cedricve** [hopkinskong/rpi-omx-jpeg-encode#2]
Hey @hopkinskong,

Would love to integrate this into the Kerberos.io project https://github.com/kerberos-io/machinery/blob/master/src/kerberos/capture/Stream.cpp#L167

Would you be interested to help?

Cédric

**Comment by hopkinskong** [comment]
Sure. You mean Raspberry Pi optimizations or just OpenCV implementations?

**Comment by cedricve** [comment]
Both, what you're most interested in.. I love the way you're using the OpenMax IL library to encode images, but have no experience, with this at all. Can you add me on skype @cedricverst
