### ISSUE TITLE
Include some example benchmark stats in the README

### ISSUE THREAD

**Issue by stuaxo** [hopkinskong/rpi-omx-jpeg-encode#6]
Hi,
   This looks like it could be really handy, any chance of including some benchmark numbers in the README, so people can get an idea before running it ?

Cheers
S

**Comment by hopkinskong** [comment]
See README.md for the test results. You are also welcomed to submit a pull request to include more numbers.

**Comment by stuaxo** [comment]
Awesome, thanks :)
